// Shared marker for dummy applicant data ("Get dummy data" on the
// Applicants page). Distinct from DUMMY_POSTING_MARKER and from
// scripts/seed.ts's @seed.jobgiga.test domain — this one is scoped
// specifically to jobseekers created for this button, so removal never
// touches real accounts or the general fake-data seed.
export const DUMMY_APPLICANT_EMAIL_DOMAIN = "dummy-applicant.jobgiga.test";

export type DummyApplicantDefinition = {
  fullName: string;
  targetRole: string;
  location: string;
  yearsExperience: number;
  skills: string[];
  softSkills: string[];
  expectedSalaryMin: number;
  expectedSalaryMax: number;
  employmentType: "full_time" | "part_time" | "contract" | "internship";
  workArrangement: "remote" | "hybrid" | "onsite";
  noticePeriod: "immediate" | "one_week" | "two_weeks" | "one_month" | "two_months" | "more_than_two_months";
  workAuthorization: "citizen" | "permanent_resident" | "work_pass_holder" | "needs_sponsorship";
  bio: string;
  // What stage to drop this application into once it's created — lets one
  // click populate both the Applicants and Interviews pages with a
  // realistic spread instead of everyone sitting at "applied".
  status: "applied" | "screened" | "shortlisted" | "interview" | "interviewed" | "evaluation" | "evaluated" | "kiv" | "offer" | "hired" | "rejected" | "withdrawn";
  interviewRound?: number;
};

// Names alone (no email available on the client-side ApplicationRow shape)
// are enough to detect "dummy data is currently present" for the toggle
// button's label — names are distinctive enough not to collide with a real
// applicant's.
export const DUMMY_APPLICANT_NAMES = [
  "Nurul Aina Rahman",
  "Wei Ling Tan",
  "Priya Suresh",
  "Aiman Hafiz Ismail",
  "Farah Aisyah Zainal",
  "Kai Xuan Lim",
  "Muhammad Danial Yusof",
  "Mei Xin Ng",
  "Deepak Kumar",
  "Siti Aisyah Hamid",
  "Zhi Hao Chong",
  "Anitha Devi",
  "Iskandar Karim",
  "Jia Hui Wong",
  "Farid Salleh",
  "Batrisyia Alia Ibrahim",
  "Chee Keong Teoh",
  "Ravi Anand",
  "Amirul Zaid Hassan",
  "Xin Yi Lee",
  "Aina Sofea Rashid",
  "Jun Wei Goh",
  "Harish Ramanathan",
  "Nabilah Izzati Rosli",
  "Yee Ling Chan",
  "Faisal Adnan",
  "Kavitha Rajendran",
  "Amirah Syazwani Zulkifli",
  "Choon Hong Lau",
  "Aleesya Batrisyia Rahim",
  "Elaine Wong Su Yi",
  "Danish Iqbal Rahman",
  "Michelle Tan Wei Xuan",
  "Arif Hidayat Zulkarnain",
  "Vikram Sivakumar",
  "Nur Hidayah Kamal",
  "Bryan Lee Zhi Wen",
  "Fatin Nabila Azman",
  "Suresh Kumaran",
  "Aina Natasha Roslan",
  "Wong Kah Yan",
  "Hafiz Rizal Osman",
  "Devika Sivaraj",
  "Nur Syafiqah Halim",
  "Tan Mei Ling",
  "Azrul Nizam Baharudin",
  "Cheryl Lim Xin Ee",
  "Muhammad Haziq Anuar",
  "Sangeetha Muniandy",
  "Farah Diyana Mokhtar",
  "Aliya Farzana Rosli",
  "Chong Wei Jian",
  "Ashwin Balakrishnan",
  "Nurul Izzah Hashim",
  "Teo Kai Ming",
  "Sharmila Devi Raman",
  "Haris Iskandar Zulkifli",
  "Yap Xin Hui",
  "Rajesh Kannan",
  "Nadia Sofia Amran",
  "Lim Jun Kai",
  "Aisyah Humaira Shah",
  "Vinesh Kumar",
  "Cheng Li Wen",
  "Faris Adnan Rahim",
  "Puteri Nur Alia",
  "Ong Zhi Yang",
  "Meera Nathan",
  "Hafiz Danial Mokhtar",
  "Sheryl Ng Wei Ting",
  "Amirah Qistina Rahman",
  "Kenji Tan Wei Hao",
  "Dinesh Waran",
  "Farhana Iman Zulkifli",
  "Bryan Chua Kai Xuan",
  "Suresh Balan",
  "Nur Alya Batrisyia",
  "Wong Jing Yi",
  "Aiman Syafiq Rosli",
  "Priyanka Devi",
  "Chang Wei Han",
  "Nabil Hakim Azman",
  "Michelle Ho Yan Ting",
  "Thivya Selvam",
  "Ariff Danish Kamal",
  "Lee Zhi Xuan",
  "Nur Ain Syazwani",
  "Karthik Selvaraj",
  "Farid Iskandar Yaacob",
  "Chloe Tan Xin Yi",
  "Hafizuddin Ramli",
  "Sasikala Muthu",
  "Aidil Haziq Mansor",
  "Wong Li Ting",
  "Rachel Anne Fernandez",
  "Zulkarnain Hafiz",
  "Nurul Syahirah Kamarudin",
  "Teoh Jun Han",
  "Shivani Ramesh",
  "Amirul Danish Rosli",
  "Chen Wei Ling",
  "Fazlina Yusof",
];

// Broader per-role skill pools — merged with each applicant's own short
// `skills` list so the profile modal shows a full, realistic-looking skill
// set (like a real jobseeker's) instead of just 2-3 tags.
const ROLE_SKILL_POOLS: Record<string, string[]> = {
  "Frontend Engineer": [
    "React",
    "TypeScript",
    "JavaScript",
    "HTML5",
    "CSS3",
    "Tailwind CSS",
    "Next.js",
    "Redux",
    "REST API Integration",
    "Responsive Design",
    "Git",
    "Webpack",
  ],
  "Backend Engineer": [
    "Node.js",
    "PostgreSQL",
    "REST API Design",
    "Docker",
    "AWS",
    "Redis",
    "System Design",
    "Unit Testing",
    "CI/CD",
    "Microservices",
    "Git",
    "Linux",
  ],
  "Store Supervisor": [
    "Inventory Management",
    "POS Systems",
    "Team Scheduling",
    "Cash Handling",
    "Customer Service",
    "Visual Merchandising",
    "Stock Control",
    "Vendor Coordination",
    "Sales Reporting",
    "Loss Prevention",
  ],
  "Registered Nurse": [
    "Patient Care",
    "Clinical Documentation",
    "Vitals Monitoring",
    "Medication Administration",
    "First Aid",
    "Infection Control",
    "Electronic Health Records",
    "Patient Assessment",
    "IV Therapy",
    "Emergency Response",
  ],
  "Marketing Intern": [
    "Social Media Management",
    "Content Writing",
    "Copywriting",
    "Canva",
    "Market Research",
    "Campaign Tracking",
    "SEO Basics",
    "Video Editing",
    "Excel",
    "Email Marketing",
  ],
};

const SOFT_SKILL_POOL = [
  "Communication",
  "Teamwork",
  "Problem solving",
  "Time management",
  "Adaptability",
  "Attention to detail",
  "Leadership",
  "Critical thinking",
];

const INSTITUTIONS = [
  "Universiti Malaya",
  "Universiti Teknologi Malaysia",
  "Universiti Kebangsaan Malaysia",
  "Multimedia University",
  "Taylor's University",
  "Sunway University",
  "Universiti Putra Malaysia",
  "INTI International University",
];

const FIELDS_OF_STUDY: Record<string, string> = {
  "Frontend Engineer": "Computer Science",
  "Backend Engineer": "Computer Science",
  "Store Supervisor": "Business Administration",
  "Registered Nurse": "Nursing",
  "Marketing Intern": "Marketing",
};

// Matches each role to the same industry used by its corresponding entry in
// DUMMY_JOB_POSTINGS (src/lib/dummy-job-postings.ts) — both drawn from
// INDUSTRIES (src/lib/industries.ts) — so the new industry-match scoring
// component actually has aligned data to demo instead of a random pairing.
export const ROLE_INDUSTRY: Record<string, string> = {
  "Frontend Engineer": "Information Technology & Software",
  "Backend Engineer": "Information Technology & Software",
  "Store Supervisor": "Retail & Consumer Goods",
  "Registered Nurse": "Healthcare & Medical",
  "Marketing Intern": "Marketing & Advertising",
};

const QUALIFICATION_TIERS = ["Diploma", "Bachelor's Degree", "Bachelor's Degree", "Master's Degree"];

const COMPANIES = [
  "Tigapuluh Solutions",
  "Bintang Retail Group",
  "Harapan Healthcare",
  "Cahaya Digital",
  "Merdeka Holdings",
  "Sinar Enterprise",
];

const CERTIFICATIONS: Record<string, string> = {
  "Frontend Engineer": "Meta Front-End Developer Certificate",
  "Backend Engineer": "AWS Certified Cloud Practitioner",
  "Store Supervisor": "Certified Retail Management Professional",
  "Registered Nurse": "Basic Life Support (BLS) Certification",
  "Marketing Intern": "Google Digital Marketing Certificate",
};

function phoneFromIndex(i: number): string {
  return `+60 1${2 + (i % 8)}-${String(1000000 + i * 137).slice(0, 3)} ${String(1000 + i * 91).slice(0, 4)}`;
}

// Deterministic per-index picks so re-running "Get dummy data" always
// produces the same enriched profile for the same applicant, rather than
// random data that shifts on every click.
export function buildDummyApplicantProfile(applicant: DummyApplicantDefinition, index: number) {
  const rolePool = ROLE_SKILL_POOLS[applicant.targetRole] ?? [];
  const existingSkillsLower = new Set(applicant.skills.map((s) => s.toLowerCase()));
  const extraSkills = rolePool.filter((s) => !existingSkillsLower.has(s.toLowerCase())).slice(0, 6);
  const extraSoftSkills = SOFT_SKILL_POOL.filter((s) => !applicant.softSkills.includes(s)).slice(0, 2);

  const currentYear = new Date().getFullYear();
  const birthYear = currentYear - (22 + applicant.yearsExperience + (index % 6));
  const graduationYear = currentYear - applicant.yearsExperience - (index % 2);

  return {
    phone: phoneFromIndex(index),
    dateOfBirth: `${birthYear}-0${(index % 9) + 1}-1${index % 9}`,
    gender: (index % 2 === 0 ? "female" : "male") as "male" | "female",
    maritalStatus: (index % 3 === 0 ? "married" : "single") as "single" | "married",
    nationality: "Malaysian",
    drivingLicense: (index % 2 === 0 ? "b" : "b2") as "b" | "b2",
    skills: [...applicant.skills, ...extraSkills],
    softSkills: [...applicant.softSkills, ...extraSoftSkills],
    education: {
      institution: INSTITUTIONS[index % INSTITUTIONS.length],
      fieldOfStudy: FIELDS_OF_STUDY[applicant.targetRole] ?? "General Studies",
      qualificationTier: QUALIFICATION_TIERS[index % QUALIFICATION_TIERS.length],
      graduationYear,
    },
    workExperience:
      applicant.yearsExperience > 0
        ? {
            company: COMPANIES[index % COMPANIES.length],
            title: applicant.targetRole,
            startDate: `${currentYear - applicant.yearsExperience}-01-01`,
            achievements: `Handled day-to-day ${applicant.targetRole.toLowerCase()} responsibilities and contributed to key team goals.`,
          }
        : null,
    certification:
      index % 2 === 0
        ? { name: CERTIFICATIONS[applicant.targetRole] ?? "Professional Certificate", issuer: "Online", year: graduationYear + 1 }
        : null,
    languages: [
      { language: "English", spokenLevel: "fluent" as const, writtenLevel: "fluent" as const },
      { language: "Bahasa Malaysia", spokenLevel: "native" as const, writtenLevel: "native" as const },
    ],
  };
}

export const DUMMY_APPLICANTS: DummyApplicantDefinition[] = [
  {
    fullName: "Nurul Aina Rahman",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["React", "TypeScript", "CSS"],
    softSkills: ["Communication", "Teamwork"],
    expectedSalaryMin: 5000,
    expectedSalaryMax: 7000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Frontend engineer with 3 years of experience building customer-facing web apps.",
    status: "applied",
  },
  {
    fullName: "Wei Ling Tan",
    targetRole: "Backend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 4,
    skills: ["Node.js", "PostgreSQL", "AWS"],
    softSkills: ["Problem solving", "Ownership"],
    expectedSalaryMin: 6500,
    expectedSalaryMax: 9000,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Backend engineer focused on scalable APIs and database design.",
    status: "screened",
  },
  {
    fullName: "Priya Suresh",
    targetRole: "Store Supervisor",
    location: "Subang Jaya",
    yearsExperience: 2,
    skills: ["Inventory management", "POS systems"],
    softSkills: ["Leadership", "Customer service"],
    expectedSalaryMin: 2800,
    expectedSalaryMax: 3500,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Retail supervisor with experience managing frontline staff and daily operations.",
    status: "shortlisted",
  },
  {
    fullName: "Aiman Hafiz Ismail",
    targetRole: "Registered Nurse",
    location: "Ipoh",
    yearsExperience: 5,
    skills: ["Patient care", "Clinical documentation"],
    softSkills: ["Empathy", "Attention to detail"],
    expectedSalaryMin: 3800,
    expectedSalaryMax: 4800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Registered nurse with 5 years of clinical experience in general wards.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Farah Aisyah Zainal",
    targetRole: "Marketing Intern",
    location: "George Town, Penang",
    yearsExperience: 0,
    skills: ["Social media", "Content writing"],
    softSkills: ["Creativity", "Adaptability"],
    expectedSalaryMin: 1200,
    expectedSalaryMax: 1600,
    employmentType: "internship",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Final-year marketing student looking for hands-on internship experience.",
    status: "interviewed",
    interviewRound: 1,
  },
  {
    fullName: "Kai Xuan Lim",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 6,
    skills: ["React", "Next.js", "GraphQL"],
    softSkills: ["Mentorship", "Communication"],
    expectedSalaryMin: 8000,
    expectedSalaryMax: 11000,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Senior frontend engineer with a track record of leading small teams.",
    status: "kiv",
  },
  {
    fullName: "Muhammad Danial Yusof",
    targetRole: "Backend Engineer",
    location: "Cyberjaya",
    yearsExperience: 2,
    skills: ["Python", "Django", "Docker"],
    softSkills: ["Curiosity", "Teamwork"],
    expectedSalaryMin: 4500,
    expectedSalaryMax: 6000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Backend developer who enjoys untangling messy legacy systems.",
    status: "evaluated",
    interviewRound: 1,
  },
  {
    fullName: "Mei Xin Ng",
    targetRole: "Marketing Intern",
    location: "Kuala Lumpur",
    yearsExperience: 0,
    skills: ["Copywriting", "Canva"],
    softSkills: ["Organized", "Adaptability"],
    expectedSalaryMin: 1000,
    expectedSalaryMax: 1500,
    employmentType: "internship",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Mass communications student eager to get hands-on marketing experience.",
    status: "applied",
  },
  {
    fullName: "Deepak Kumar",
    targetRole: "Store Supervisor",
    location: "Johor Bahru",
    yearsExperience: 4,
    skills: ["Team management", "Cash handling"],
    softSkills: ["Leadership", "Patience"],
    expectedSalaryMin: 3000,
    expectedSalaryMax: 3800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Retail supervisor experienced in managing shift schedules and stock counts.",
    status: "offer",
  },
  {
    fullName: "Siti Aisyah Hamid",
    targetRole: "Registered Nurse",
    location: "Malacca City",
    yearsExperience: 3,
    skills: ["Patient care", "Vitals monitoring"],
    softSkills: ["Compassion", "Composure under pressure"],
    expectedSalaryMin: 3600,
    expectedSalaryMax: 4500,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Nurse with experience in both ward care and outpatient clinics.",
    status: "screened",
  },
  {
    fullName: "Zhi Hao Chong",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 1,
    skills: ["Vue", "JavaScript"],
    softSkills: ["Fast learner", "Communication"],
    expectedSalaryMin: 3800,
    expectedSalaryMax: 5000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Junior frontend developer transitioning from a bootcamp into full-time work.",
    status: "rejected",
  },
  {
    fullName: "Anitha Devi",
    targetRole: "Backend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 7,
    skills: ["Java", "Spring Boot", "Kubernetes"],
    softSkills: ["Ownership", "Mentorship"],
    expectedSalaryMin: 9000,
    expectedSalaryMax: 12000,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Senior backend engineer specializing in distributed systems.",
    status: "shortlisted",
  },
  {
    fullName: "Iskandar Karim",
    targetRole: "Marketing Intern",
    location: "Shah Alam",
    yearsExperience: 0,
    skills: ["Video editing", "Social media"],
    softSkills: ["Creativity", "Punctuality"],
    expectedSalaryMin: 1000,
    expectedSalaryMax: 1400,
    employmentType: "internship",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Content creator looking to bring short-form video skills to a brand's socials.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Jia Hui Wong",
    targetRole: "Store Supervisor",
    location: "Kuching",
    yearsExperience: 3,
    skills: ["Inventory management", "Scheduling"],
    softSkills: ["Leadership", "Customer service"],
    expectedSalaryMin: 2900,
    expectedSalaryMax: 3700,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Assistant store manager ready to step up into a full supervisor role.",
    status: "hired",
  },
  {
    fullName: "Farid Salleh",
    targetRole: "Registered Nurse",
    location: "Kuala Lumpur",
    yearsExperience: 1,
    skills: ["Patient care", "First aid"],
    softSkills: ["Empathy", "Team player"],
    expectedSalaryMin: 3200,
    expectedSalaryMax: 3900,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Newly registered nurse looking for their first full-time clinical role.",
    status: "applied",
  },
  {
    fullName: "Batrisyia Alia Ibrahim",
    targetRole: "Frontend Engineer",
    location: "Seremban",
    yearsExperience: 2,
    skills: ["React", "Redux"],
    softSkills: ["Detail-oriented", "Communication"],
    expectedSalaryMin: 4800,
    expectedSalaryMax: 6200,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Frontend developer with a strong eye for pixel-accurate implementation.",
    status: "interviewed",
    interviewRound: 2,
  },
  {
    fullName: "Chee Keong Teoh",
    targetRole: "Backend Engineer",
    location: "George Town, Penang",
    yearsExperience: 5,
    skills: ["Go", "PostgreSQL", "Redis"],
    softSkills: ["Problem solving", "Ownership"],
    expectedSalaryMin: 7500,
    expectedSalaryMax: 10000,
    employmentType: "contract",
    workArrangement: "remote",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Contract backend engineer specializing in high-throughput services.",
    status: "kiv",
  },
  {
    fullName: "Ravi Anand",
    targetRole: "Marketing Intern",
    location: "Petaling Jaya",
    yearsExperience: 0,
    skills: ["Market research", "Excel"],
    softSkills: ["Analytical", "Adaptability"],
    expectedSalaryMin: 1100,
    expectedSalaryMax: 1500,
    employmentType: "internship",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Business student interested in the analytics side of marketing.",
    status: "screened",
  },
  {
    fullName: "Amirul Zaid Hassan",
    targetRole: "Store Supervisor",
    location: "Alor Setar",
    yearsExperience: 6,
    skills: ["Team management", "Vendor coordination"],
    softSkills: ["Leadership", "Negotiation"],
    expectedSalaryMin: 3300,
    expectedSalaryMax: 4200,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Multi-outlet retail supervisor looking for a bigger single-store role.",
    status: "evaluated",
    interviewRound: 1,
  },
  {
    fullName: "Xin Yi Lee",
    targetRole: "Registered Nurse",
    location: "Miri",
    yearsExperience: 8,
    skills: ["Clinical documentation", "Team leadership"],
    softSkills: ["Composure under pressure", "Mentorship"],
    expectedSalaryMin: 4500,
    expectedSalaryMax: 5500,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Senior nurse with experience supervising junior clinical staff.",
    status: "shortlisted",
  },
  // 10 additional applicants — 2 per role, employmentType/workArrangement
  // aligned to that role's DUMMY_JOB_POSTINGS entry (a couple deliberately
  // varied) so the new matching components have both strong and partial
  // matches to demo, not just perfect scores across the board.
  {
    fullName: "Aina Sofea Rashid",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 2,
    skills: ["React", "JavaScript", "CSS"],
    softSkills: ["Communication", "Fast learner"],
    expectedSalaryMin: 4200,
    expectedSalaryMax: 5800,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Frontend developer who enjoys turning Figma designs into pixel-accurate components.",
    status: "applied",
  },
  {
    fullName: "Jun Wei Goh",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 4,
    skills: ["React", "TypeScript", "Next.js"],
    softSkills: ["Teamwork", "Attention to detail"],
    expectedSalaryMin: 6000,
    expectedSalaryMax: 8000,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Frontend engineer who has shipped design systems for two SaaS products.",
    status: "screened",
  },
  {
    fullName: "Harish Ramanathan",
    targetRole: "Backend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 3,
    skills: ["Node.js", "PostgreSQL", "Docker"],
    softSkills: ["Problem solving", "Communication"],
    expectedSalaryMin: 6200,
    expectedSalaryMax: 8500,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Backend engineer with a focus on clean API design and database performance.",
    status: "shortlisted",
  },
  {
    fullName: "Nabilah Izzati Rosli",
    targetRole: "Backend Engineer",
    location: "Cyberjaya",
    yearsExperience: 1,
    skills: ["Node.js", "MongoDB"],
    softSkills: ["Curiosity", "Teamwork"],
    expectedSalaryMin: 4000,
    expectedSalaryMax: 5200,
    employmentType: "contract",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Junior backend developer looking to grow into a full-stack role.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Yee Ling Chan",
    targetRole: "Store Supervisor",
    location: "Subang Jaya",
    yearsExperience: 3,
    skills: ["Inventory management", "Team scheduling"],
    softSkills: ["Leadership", "Customer service"],
    expectedSalaryMin: 3000,
    expectedSalaryMax: 3800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Retail supervisor experienced in running a mid-sized outlet's daily operations.",
    status: "interviewed",
    interviewRound: 1,
  },
  {
    fullName: "Faisal Adnan",
    targetRole: "Store Supervisor",
    location: "Subang Jaya",
    yearsExperience: 5,
    skills: ["POS systems", "Vendor coordination"],
    softSkills: ["Negotiation", "Patience"],
    expectedSalaryMin: 3200,
    expectedSalaryMax: 4000,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Store supervisor with a track record of reducing stock discrepancies.",
    status: "evaluated",
    interviewRound: 1,
  },
  {
    fullName: "Kavitha Rajendran",
    targetRole: "Registered Nurse",
    location: "Ipoh",
    yearsExperience: 4,
    skills: ["Patient care", "IV Therapy"],
    softSkills: ["Empathy", "Composure under pressure"],
    expectedSalaryMin: 3900,
    expectedSalaryMax: 4700,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Registered nurse experienced in both general wards and emergency response.",
    status: "kiv",
  },
  {
    fullName: "Amirah Syazwani Zulkifli",
    targetRole: "Registered Nurse",
    location: "Ipoh",
    yearsExperience: 6,
    skills: ["Clinical documentation", "Medication administration"],
    softSkills: ["Attention to detail", "Team player"],
    expectedSalaryMin: 4200,
    expectedSalaryMax: 5200,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Nurse with strong clinical documentation habits and a calm bedside manner.",
    status: "offer",
  },
  {
    fullName: "Choon Hong Lau",
    targetRole: "Marketing Intern",
    location: "George Town, Penang",
    yearsExperience: 0,
    skills: ["Content writing", "SEO Basics"],
    softSkills: ["Adaptability", "Organized"],
    expectedSalaryMin: 1200,
    expectedSalaryMax: 1600,
    employmentType: "internship",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Communications student who runs a small lifestyle blog on the side.",
    status: "hired",
  },
  {
    fullName: "Aleesya Batrisyia Rahim",
    targetRole: "Marketing Intern",
    location: "George Town, Penang",
    yearsExperience: 0,
    skills: ["Social media", "Video editing"],
    softSkills: ["Creativity", "Punctuality"],
    expectedSalaryMin: 1000,
    expectedSalaryMax: 1400,
    employmentType: "internship",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Aspiring marketer building a portfolio of short-form video content.",
    status: "rejected",
  },
  // 20 more applicants — 4 per role, same alignment approach as the
  // previous batch (employmentType/workArrangement mostly matching that
  // role's DUMMY_JOB_POSTINGS entry, with a few deliberate mismatches),
  // spread across every pipeline status twice over.
  {
    fullName: "Elaine Wong Su Yi",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["React", "TypeScript", "CSS3"],
    softSkills: ["Communication", "Attention to detail"],
    expectedSalaryMin: 5200,
    expectedSalaryMax: 7200,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Frontend engineer who cares deeply about accessibility and clean component APIs.",
    status: "applied",
  },
  {
    fullName: "Danish Iqbal Rahman",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 1,
    skills: ["React", "JavaScript"],
    softSkills: ["Fast learner", "Teamwork"],
    expectedSalaryMin: 3600,
    expectedSalaryMax: 4600,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Bootcamp graduate who has shipped two personal full-stack side projects.",
    status: "screened",
  },
  {
    fullName: "Michelle Tan Wei Xuan",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 5,
    skills: ["React", "Next.js", "TypeScript"],
    softSkills: ["Mentorship", "Communication"],
    expectedSalaryMin: 7000,
    expectedSalaryMax: 9500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Frontend engineer who has led UI rewrites for two growth-stage startups.",
    status: "shortlisted",
  },
  {
    fullName: "Arif Hidayat Zulkarnain",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 2,
    skills: ["Vue", "React", "Tailwind CSS"],
    softSkills: ["Adaptability", "Problem solving"],
    expectedSalaryMin: 4600,
    expectedSalaryMax: 6000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Frontend developer comfortable moving between React and Vue codebases.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Vikram Sivakumar",
    targetRole: "Backend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 6,
    skills: ["Node.js", "PostgreSQL", "Kubernetes"],
    softSkills: ["Ownership", "Mentorship"],
    expectedSalaryMin: 8500,
    expectedSalaryMax: 11000,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Senior backend engineer who has taken two services from monolith to microservices.",
    status: "interviewed",
    interviewRound: 1,
  },
  {
    fullName: "Nur Hidayah Kamal",
    targetRole: "Backend Engineer",
    location: "Cyberjaya",
    yearsExperience: 2,
    skills: ["Node.js", "Express", "MySQL"],
    softSkills: ["Curiosity", "Communication"],
    expectedSalaryMin: 4800,
    expectedSalaryMax: 6200,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Backend developer with a habit of writing thorough API documentation.",
    status: "evaluated",
    interviewRound: 1,
  },
  {
    fullName: "Bryan Lee Zhi Wen",
    targetRole: "Backend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 4,
    skills: ["Node.js", "PostgreSQL", "AWS"],
    softSkills: ["Problem solving", "Ownership"],
    expectedSalaryMin: 6800,
    expectedSalaryMax: 9000,
    employmentType: "contract",
    workArrangement: "remote",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Backend engineer who prefers contract work across a few products at once.",
    status: "kiv",
  },
  {
    fullName: "Fatin Nabila Azman",
    targetRole: "Backend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["Node.js", "PostgreSQL", "Docker"],
    softSkills: ["Teamwork", "Attention to detail"],
    expectedSalaryMin: 6000,
    expectedSalaryMax: 8000,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Backend engineer who enjoys untangling flaky test suites and CI pipelines.",
    status: "offer",
  },
  {
    fullName: "Suresh Kumaran",
    targetRole: "Store Supervisor",
    location: "Subang Jaya",
    yearsExperience: 7,
    skills: ["Team management", "Inventory management"],
    softSkills: ["Leadership", "Negotiation"],
    expectedSalaryMin: 3400,
    expectedSalaryMax: 4200,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Multi-year store supervisor who has trained several junior staff into leads.",
    status: "hired",
  },
  {
    fullName: "Aina Natasha Roslan",
    targetRole: "Store Supervisor",
    location: "Subang Jaya",
    yearsExperience: 1,
    skills: ["POS systems", "Customer service"],
    softSkills: ["Patience", "Communication"],
    expectedSalaryMin: 2500,
    expectedSalaryMax: 3000,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Former retail associate stepping up into her first supervisory role.",
    status: "rejected",
  },
  {
    fullName: "Wong Kah Yan",
    targetRole: "Store Supervisor",
    location: "Petaling Jaya",
    yearsExperience: 4,
    skills: ["Inventory management", "Vendor coordination"],
    softSkills: ["Leadership", "Customer service"],
    expectedSalaryMin: 3100,
    expectedSalaryMax: 3900,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Store supervisor experienced in seasonal staffing and stocktake cycles.",
    status: "applied",
  },
  {
    fullName: "Hafiz Rizal Osman",
    targetRole: "Store Supervisor",
    location: "Subang Jaya",
    yearsExperience: 2,
    skills: ["Team scheduling", "Cash handling"],
    softSkills: ["Organized", "Patience"],
    expectedSalaryMin: 2900,
    expectedSalaryMax: 3500,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Assistant supervisor with a strong track record on shift scheduling.",
    status: "screened",
  },
  {
    fullName: "Devika Sivaraj",
    targetRole: "Registered Nurse",
    location: "Ipoh",
    yearsExperience: 2,
    skills: ["Patient care", "Vitals monitoring"],
    softSkills: ["Empathy", "Team player"],
    expectedSalaryMin: 3500,
    expectedSalaryMax: 4200,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Nurse with two years of general ward experience, now looking to specialize.",
    status: "shortlisted",
  },
  {
    fullName: "Nur Syafiqah Halim",
    targetRole: "Registered Nurse",
    location: "Ipoh",
    yearsExperience: 5,
    skills: ["Clinical documentation", "IV Therapy"],
    softSkills: ["Composure under pressure", "Attention to detail"],
    expectedSalaryMin: 4000,
    expectedSalaryMax: 4900,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Nurse experienced in both ward rotations and short-staffed night shifts.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Tan Mei Ling",
    targetRole: "Registered Nurse",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["Patient care", "Medication administration"],
    softSkills: ["Empathy", "Communication"],
    expectedSalaryMin: 3700,
    expectedSalaryMax: 4500,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Nurse who recently relocated to Kuala Lumpur and is restarting her clinical career here.",
    status: "interviewed",
    interviewRound: 2,
  },
  {
    fullName: "Azrul Nizam Baharudin",
    targetRole: "Registered Nurse",
    location: "Ipoh",
    yearsExperience: 9,
    skills: ["Clinical documentation", "Team leadership", "Emergency response"],
    softSkills: ["Mentorship", "Composure under pressure"],
    expectedSalaryMin: 4800,
    expectedSalaryMax: 5800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Senior nurse who has supervised ward rotations across three hospitals.",
    status: "evaluated",
    interviewRound: 1,
  },
  {
    fullName: "Cheryl Lim Xin Ee",
    targetRole: "Marketing Intern",
    location: "George Town, Penang",
    yearsExperience: 0,
    skills: ["Market research", "Excel"],
    softSkills: ["Analytical", "Organized"],
    expectedSalaryMin: 1000,
    expectedSalaryMax: 1400,
    employmentType: "internship",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Business analytics student drawn to the data side of marketing campaigns.",
    status: "kiv",
  },
  {
    fullName: "Muhammad Haziq Anuar",
    targetRole: "Marketing Intern",
    location: "George Town, Penang",
    yearsExperience: 0,
    skills: ["Content writing", "Copywriting"],
    softSkills: ["Creativity", "Fast learner"],
    expectedSalaryMin: 1200,
    expectedSalaryMax: 1600,
    employmentType: "internship",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Journalism student with a portfolio of published campus newsletter articles.",
    status: "offer",
  },
  {
    fullName: "Sangeetha Muniandy",
    targetRole: "Marketing Intern",
    location: "George Town, Penang",
    yearsExperience: 0,
    skills: ["Social media", "Canva"],
    softSkills: ["Creativity", "Adaptability"],
    expectedSalaryMin: 1100,
    expectedSalaryMax: 1500,
    employmentType: "internship",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Runs a growing food-review Instagram page alongside her studies.",
    status: "hired",
  },
  {
    fullName: "Farah Diyana Mokhtar",
    targetRole: "Marketing Intern",
    location: "George Town, Penang",
    yearsExperience: 0,
    skills: ["SEO Basics", "Email Marketing"],
    softSkills: ["Organized", "Communication"],
    expectedSalaryMin: 1000,
    expectedSalaryMax: 1300,
    employmentType: "internship",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Marketing student interested in the technical side of SEO and email funnels.",
    status: "rejected",
  },
  {
    fullName: "Aliya Farzana Rosli",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 1,
    skills: ["React", "JavaScript", "HTML5"],
    softSkills: ["Communication", "Adaptability"],
    expectedSalaryMin: 4200,
    expectedSalaryMax: 5500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Junior frontend developer who recently transitioned from a bootcamp into her first full-time role.",
    status: "applied",
  },
  {
    fullName: "Chong Wei Jian",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 4,
    skills: ["React", "TypeScript", "Next.js"],
    softSkills: ["Problem solving", "Attention to detail"],
    expectedSalaryMin: 6500,
    expectedSalaryMax: 8500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Frontend engineer who has shipped several customer-facing dashboards using React and TypeScript.",
    status: "screened",
  },
  {
    fullName: "Ashwin Balakrishnan",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["React", "Tailwind CSS", "Redux"],
    softSkills: ["Teamwork", "Communication"],
    expectedSalaryMin: 5500,
    expectedSalaryMax: 7500,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Comfortable owning a feature end-to-end, from component design to state management.",
    status: "shortlisted",
  },
  {
    fullName: "Nurul Izzah Hashim",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 2,
    skills: ["React", "TypeScript", "CSS"],
    softSkills: ["Attention to detail", "Time management"],
    expectedSalaryMin: 4800,
    expectedSalaryMax: 6200,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Built and maintained a component library used across three internal products.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Teo Kai Ming",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 5,
    skills: ["React", "Next.js", "GraphQL"],
    softSkills: ["Mentorship", "Communication"],
    expectedSalaryMin: 7500,
    expectedSalaryMax: 9500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Led the migration of a legacy jQuery app to React, cutting page load times by half.",
    status: "interviewed",
    interviewRound: 1,
  },
  {
    fullName: "Sharmila Devi Raman",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 3,
    skills: ["React", "TypeScript", "Testing (Jest/Playwright)"],
    softSkills: ["Attention to detail", "Ownership"],
    expectedSalaryMin: 6000,
    expectedSalaryMax: 7800,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Strong advocate for test coverage — introduced Playwright end-to-end tests at her current job.",
    status: "evaluation",
    interviewRound: 2,
  },
  {
    fullName: "Haris Iskandar Zulkifli",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 4,
    skills: ["React", "TypeScript", "Accessibility (WCAG)"],
    softSkills: ["Communication", "Attention to detail"],
    expectedSalaryMin: 6800,
    expectedSalaryMax: 8800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Championed accessibility improvements that brought his current team's app up to WCAG AA.",
    status: "evaluated",
    interviewRound: 2,
  },
  {
    fullName: "Yap Xin Hui",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 6,
    skills: ["React", "Next.js", "TypeScript"],
    softSkills: ["Leadership", "Mentorship"],
    expectedSalaryMin: 8500,
    expectedSalaryMax: 11000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Senior frontend engineer weighing this offer against a competing one — strong candidate overall.",
    status: "kiv",
  },
  {
    fullName: "Rajesh Kannan",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 5,
    skills: ["React", "TypeScript", "GraphQL"],
    softSkills: ["Problem solving", "Communication"],
    expectedSalaryMin: 7500,
    expectedSalaryMax: 9500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Impressed the panel with a live coding round — offer being finalized.",
    status: "offer",
    interviewRound: 2,
  },
  {
    fullName: "Nadia Sofia Amran",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 4,
    skills: ["React", "TypeScript", "Next.js"],
    softSkills: ["Communication", "Teamwork"],
    expectedSalaryMin: 6500,
    expectedSalaryMax: 8500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Accepted the offer and starts next month — excited to join the product team.",
    status: "hired",
    interviewRound: 2,
  },
  {
    fullName: "Lim Jun Kai",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 2,
    skills: ["React", "JavaScript", "CSS"],
    softSkills: ["Adaptability", "Time management"],
    expectedSalaryMin: 4500,
    expectedSalaryMax: 5800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Solid fundamentals but skills didn't stretch far enough beyond basic React for this role.",
    status: "rejected",
  },
  {
    fullName: "Aisyah Humaira Shah",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["React", "TypeScript", "Tailwind CSS"],
    softSkills: ["Communication", "Adaptability"],
    expectedSalaryMin: 5800,
    expectedSalaryMax: 7200,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Withdrew her application after accepting a counteroffer from her current employer.",
    status: "withdrawn",
  },
  {
    fullName: "Vinesh Kumar",
    targetRole: "Frontend Engineer",
    location: "Subang Jaya",
    yearsExperience: 2,
    skills: ["React", "TypeScript", "Redux"],
    softSkills: ["Teamwork", "Problem solving"],
    expectedSalaryMin: 5000,
    expectedSalaryMax: 6500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Two years building internal tooling in React, now looking for a customer-facing product role.",
    status: "applied",
  },
  {
    fullName: "Cheng Li Wen",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["React", "TypeScript", "Next.js"],
    softSkills: ["Attention to detail", "Communication"],
    expectedSalaryMin: 6000,
    expectedSalaryMax: 7500,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Built a personal SaaS side project in Next.js that now has a few hundred paying users.",
    status: "screened",
  },
  {
    fullName: "Faris Adnan Rahim",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 4,
    skills: ["React", "TypeScript", "GraphQL"],
    softSkills: ["Ownership", "Communication"],
    expectedSalaryMin: 6800,
    expectedSalaryMax: 8500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Owns the frontend architecture for a mid-sized fintech product at his current job.",
    status: "shortlisted",
  },
  {
    fullName: "Puteri Nur Alia",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 1,
    skills: ["React", "JavaScript", "Tailwind CSS"],
    softSkills: ["Adaptability", "Communication"],
    expectedSalaryMin: 4300,
    expectedSalaryMax: 5500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "First job out of university — built her portfolio site and two group projects in React.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Ong Zhi Yang",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 5,
    skills: ["React", "TypeScript", "Testing (Jest/Playwright)"],
    softSkills: ["Mentorship", "Problem solving"],
    expectedSalaryMin: 7500,
    expectedSalaryMax: 9500,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Five years across two startups, most recently as the most senior frontend engineer on his team.",
    status: "interviewed",
    interviewRound: 1,
  },
  {
    fullName: "Meera Nathan",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 3,
    skills: ["React", "TypeScript", "Figma"],
    softSkills: ["Communication", "Attention to detail"],
    expectedSalaryMin: 5800,
    expectedSalaryMax: 7200,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Works closely with designers and often translates Figma files into components herself.",
    status: "evaluation",
    interviewRound: 2,
  },
  {
    fullName: "Hafiz Danial Mokhtar",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 2,
    skills: ["React", "JavaScript", "CSS"],
    softSkills: ["Teamwork", "Time management"],
    expectedSalaryMin: 4800,
    expectedSalaryMax: 6000,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Comfortable turning static designs into responsive, pixel-accurate pages quickly.",
    status: "kiv",
  },
  {
    fullName: "Sheryl Ng Wei Ting",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 4,
    skills: ["React", "Next.js", "TypeScript"],
    softSkills: ["Communication", "Ownership"],
    expectedSalaryMin: 6800,
    expectedSalaryMax: 8800,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Has consistently owned performance work — cut bundle size by 30% on her current team's app.",
    status: "evaluated",
    interviewRound: 2,
  },
  {
    fullName: "Amirah Qistina Rahman",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 2,
    skills: ["React", "TypeScript", "CSS"],
    softSkills: ["Communication", "Adaptability"],
    expectedSalaryMin: 4900,
    expectedSalaryMax: 6200,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Two years into her career, with a strong eye for translating designs into clean React components.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Kenji Tan Wei Hao",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 3,
    skills: ["React", "TypeScript", "Next.js"],
    softSkills: ["Problem solving", "Teamwork"],
    expectedSalaryMin: 5800,
    expectedSalaryMax: 7400,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Rebuilt his current team's checkout flow in Next.js, cutting drop-off by double digits.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Dinesh Waran",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 4,
    skills: ["React", "TypeScript", "GraphQL"],
    softSkills: ["Ownership", "Communication"],
    expectedSalaryMin: 6500,
    expectedSalaryMax: 8200,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Full-stack leaning frontend engineer who's comfortable owning GraphQL schema changes too.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Farhana Iman Zulkifli",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 1,
    skills: ["React","TypeScript","CSS"],
    softSkills: ["Communication","Teamwork"],
    expectedSalaryMin: 4700,
    expectedSalaryMax: 6500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Frontend engineer eager to bring strong React fundamentals to a fast-moving product team.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Bryan Chua Kai Xuan",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 2,
    skills: ["React","JavaScript","HTML5"],
    softSkills: ["Problem solving","Attention to detail"],
    expectedSalaryMin: 5200,
    expectedSalaryMax: 7300,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Has spent recent years polishing component architecture and design-system consistency.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Suresh Balan",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 3,
    skills: ["React","Next.js","TypeScript"],
    softSkills: ["Adaptability","Communication"],
    expectedSalaryMin: 5700,
    expectedSalaryMax: 8100,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Enjoys turning ambiguous design specs into pixel-accurate, accessible interfaces.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Nur Alya Batrisyia",
    targetRole: "Frontend Engineer",
    location: "Subang Jaya",
    yearsExperience: 4,
    skills: ["React","Tailwind CSS","Redux"],
    softSkills: ["Ownership","Communication"],
    expectedSalaryMin: 6200,
    expectedSalaryMax: 8000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Recently led a small frontend revamp that improved page load times noticeably.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Wong Jing Yi",
    targetRole: "Frontend Engineer",
    location: "Cyberjaya",
    yearsExperience: 5,
    skills: ["React","TypeScript","GraphQL"],
    softSkills: ["Teamwork","Time management"],
    expectedSalaryMin: 6700,
    expectedSalaryMax: 8800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Comfortable pairing with backend engineers to shape clean, well-typed API contracts.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Aiman Syafiq Rosli",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 6,
    skills: ["React","TypeScript","Testing (Jest/Playwright)"],
    softSkills: ["Communication","Teamwork"],
    expectedSalaryMin: 7200,
    expectedSalaryMax: 9600,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Brings a strong testing habit, catching regressions before they reach production.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Priyanka Devi",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 1,
    skills: ["React","TypeScript","CSS"],
    softSkills: ["Problem solving","Attention to detail"],
    expectedSalaryMin: 4700,
    expectedSalaryMax: 6500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Has mentored junior developers while still shipping features on a tight sprint cadence.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Chang Wei Han",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 2,
    skills: ["React","JavaScript","HTML5"],
    softSkills: ["Adaptability","Communication"],
    expectedSalaryMin: 5200,
    expectedSalaryMax: 7300,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Passionate about performance — has shaved meaningful time off render-heavy pages before.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Nabil Hakim Azman",
    targetRole: "Frontend Engineer",
    location: "Subang Jaya",
    yearsExperience: 3,
    skills: ["React","Next.js","TypeScript"],
    softSkills: ["Ownership","Communication"],
    expectedSalaryMin: 5700,
    expectedSalaryMax: 8100,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Frontend engineer eager to bring strong React fundamentals to a fast-moving product team.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Michelle Ho Yan Ting",
    targetRole: "Frontend Engineer",
    location: "Cyberjaya",
    yearsExperience: 4,
    skills: ["React","Tailwind CSS","Redux"],
    softSkills: ["Teamwork","Time management"],
    expectedSalaryMin: 6200,
    expectedSalaryMax: 8000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Has spent recent years polishing component architecture and design-system consistency.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Thivya Selvam",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 5,
    skills: ["React","TypeScript","GraphQL"],
    softSkills: ["Communication","Teamwork"],
    expectedSalaryMin: 6700,
    expectedSalaryMax: 8800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Enjoys turning ambiguous design specs into pixel-accurate, accessible interfaces.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Ariff Danish Kamal",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 6,
    skills: ["React","TypeScript","Testing (Jest/Playwright)"],
    softSkills: ["Problem solving","Attention to detail"],
    expectedSalaryMin: 7200,
    expectedSalaryMax: 9600,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Recently led a small frontend revamp that improved page load times noticeably.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Lee Zhi Xuan",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 1,
    skills: ["React","TypeScript","CSS"],
    softSkills: ["Adaptability","Communication"],
    expectedSalaryMin: 4700,
    expectedSalaryMax: 6500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Comfortable pairing with backend engineers to shape clean, well-typed API contracts.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Nur Ain Syazwani",
    targetRole: "Frontend Engineer",
    location: "Subang Jaya",
    yearsExperience: 2,
    skills: ["React","JavaScript","HTML5"],
    softSkills: ["Ownership","Communication"],
    expectedSalaryMin: 5200,
    expectedSalaryMax: 7300,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Brings a strong testing habit, catching regressions before they reach production.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Karthik Selvaraj",
    targetRole: "Frontend Engineer",
    location: "Cyberjaya",
    yearsExperience: 3,
    skills: ["React","Next.js","TypeScript"],
    softSkills: ["Teamwork","Time management"],
    expectedSalaryMin: 5700,
    expectedSalaryMax: 8100,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Has mentored junior developers while still shipping features on a tight sprint cadence.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Farid Iskandar Yaacob",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 4,
    skills: ["React","Tailwind CSS","Redux"],
    softSkills: ["Communication","Teamwork"],
    expectedSalaryMin: 6200,
    expectedSalaryMax: 8000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Passionate about performance — has shaved meaningful time off render-heavy pages before.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Chloe Tan Xin Yi",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 5,
    skills: ["React","TypeScript","GraphQL"],
    softSkills: ["Problem solving","Attention to detail"],
    expectedSalaryMin: 6700,
    expectedSalaryMax: 8800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Frontend engineer eager to bring strong React fundamentals to a fast-moving product team.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Hafizuddin Ramli",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 6,
    skills: ["React","TypeScript","Testing (Jest/Playwright)"],
    softSkills: ["Adaptability","Communication"],
    expectedSalaryMin: 7200,
    expectedSalaryMax: 9600,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Has spent recent years polishing component architecture and design-system consistency.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Sasikala Muthu",
    targetRole: "Frontend Engineer",
    location: "Subang Jaya",
    yearsExperience: 1,
    skills: ["React","TypeScript","CSS"],
    softSkills: ["Ownership","Communication"],
    expectedSalaryMin: 4700,
    expectedSalaryMax: 6500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Enjoys turning ambiguous design specs into pixel-accurate, accessible interfaces.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Aidil Haziq Mansor",
    targetRole: "Frontend Engineer",
    location: "Cyberjaya",
    yearsExperience: 2,
    skills: ["React","JavaScript","HTML5"],
    softSkills: ["Teamwork","Time management"],
    expectedSalaryMin: 5200,
    expectedSalaryMax: 7300,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Recently led a small frontend revamp that improved page load times noticeably.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Wong Li Ting",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 3,
    skills: ["React","Next.js","TypeScript"],
    softSkills: ["Communication","Teamwork"],
    expectedSalaryMin: 5700,
    expectedSalaryMax: 8100,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Comfortable pairing with backend engineers to shape clean, well-typed API contracts.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Rachel Anne Fernandez",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 4,
    skills: ["React","Tailwind CSS","Redux"],
    softSkills: ["Problem solving","Attention to detail"],
    expectedSalaryMin: 6200,
    expectedSalaryMax: 8000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Brings a strong testing habit, catching regressions before they reach production.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Zulkarnain Hafiz",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 5,
    skills: ["React","TypeScript","GraphQL"],
    softSkills: ["Adaptability","Communication"],
    expectedSalaryMin: 6700,
    expectedSalaryMax: 8800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Has mentored junior developers while still shipping features on a tight sprint cadence.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Nurul Syahirah Kamarudin",
    targetRole: "Frontend Engineer",
    location: "Subang Jaya",
    yearsExperience: 6,
    skills: ["React","TypeScript","Testing (Jest/Playwright)"],
    softSkills: ["Ownership","Communication"],
    expectedSalaryMin: 7200,
    expectedSalaryMax: 9600,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Passionate about performance — has shaved meaningful time off render-heavy pages before.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Teoh Jun Han",
    targetRole: "Frontend Engineer",
    location: "Cyberjaya",
    yearsExperience: 1,
    skills: ["React","TypeScript","CSS"],
    softSkills: ["Teamwork","Time management"],
    expectedSalaryMin: 4700,
    expectedSalaryMax: 6500,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Frontend engineer eager to bring strong React fundamentals to a fast-moving product team.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Shivani Ramesh",
    targetRole: "Frontend Engineer",
    location: "Kuala Lumpur",
    yearsExperience: 2,
    skills: ["React","JavaScript","HTML5"],
    softSkills: ["Communication","Teamwork"],
    expectedSalaryMin: 5200,
    expectedSalaryMax: 7300,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "two_weeks",
    workAuthorization: "citizen",
    bio: "Has spent recent years polishing component architecture and design-system consistency.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Amirul Danish Rosli",
    targetRole: "Frontend Engineer",
    location: "Petaling Jaya",
    yearsExperience: 3,
    skills: ["React","Next.js","TypeScript"],
    softSkills: ["Problem solving","Attention to detail"],
    expectedSalaryMin: 5700,
    expectedSalaryMax: 8100,
    employmentType: "full_time",
    workArrangement: "remote",
    noticePeriod: "one_month",
    workAuthorization: "citizen",
    bio: "Enjoys turning ambiguous design specs into pixel-accurate, accessible interfaces.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Chen Wei Ling",
    targetRole: "Frontend Engineer",
    location: "Shah Alam",
    yearsExperience: 4,
    skills: ["React","Tailwind CSS","Redux"],
    softSkills: ["Adaptability","Communication"],
    expectedSalaryMin: 6200,
    expectedSalaryMax: 8000,
    employmentType: "full_time",
    workArrangement: "hybrid",
    noticePeriod: "two_months",
    workAuthorization: "citizen",
    bio: "Recently led a small frontend revamp that improved page load times noticeably.",
    status: "interview",
    interviewRound: 1,
  },
  {
    fullName: "Fazlina Yusof",
    targetRole: "Frontend Engineer",
    location: "Subang Jaya",
    yearsExperience: 5,
    skills: ["React","TypeScript","GraphQL"],
    softSkills: ["Ownership","Communication"],
    expectedSalaryMin: 6700,
    expectedSalaryMax: 8800,
    employmentType: "full_time",
    workArrangement: "onsite",
    noticePeriod: "immediate",
    workAuthorization: "citizen",
    bio: "Comfortable pairing with backend engineers to shape clean, well-typed API contracts.",
    status: "interview",
    interviewRound: 1,
  },
];
