// Shared across employer job postings, jobseeker profiles, and the seed
// script — keeps "industry" comparable on both sides of matching instead of
// three independently-drifting copies of the same three values.
//
// Comprehensive taxonomy covering major sectors in Malaysian job market,
// aligned with Malaysia Standard Industrial Classification (MSIC) but
// simplified for jobseeker/employer clarity.
export const INDUSTRIES = [
  "Accounting & Finance",
  "Administrative & Office Support",
  "Agriculture, Forestry & Fishing",
  "Architecture & Engineering",
  "Arts, Media & Communications",
  "Automotive & Transportation Equipment",
  "Aviation & Aerospace",
  "Banking & Financial Services",
  "Beauty, Wellness & Personal Care",
  "Biotechnology & Life Sciences",
  "Chemicals & Pharmaceuticals",
  "Construction & Building",
  "Consulting & Strategy",
  "Customer Service & Support",
  "Education & Training",
  "Electronics & Semiconductors",
  "Energy & Utilities",
  "Entertainment, Gaming & Recreation",
  "Environmental Services & Sustainability",
  "Event Management & Wedding Planning",
  "Facilities Management & Maintenance",
  "Fashion, Apparel & Textiles",
  "Food & Beverage Services",
  "Government & Public Service",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Human Resources & Recruitment",
  "Information Technology & Software",
  "Insurance",
  "Interior Design & Furniture",
  "Legal Services",
  "Logistics & Supply Chain",
  "Manufacturing & Production",
  "Maritime & Shipping",
  "Marketing & Advertising",
  "Media, Broadcasting & Publishing",
  "Mining & Quarrying",
  "Non-Profit & NGO",
  "Oil & Gas",
  "Printing & Packaging",
  "Property & Real Estate",
  "Public Relations & Corporate Communications",
  "Retail & Consumer Goods",
  "Sales & Business Development",
  "Science & Research",
  "Security & Law Enforcement",
  "Sports & Fitness",
  "Telecommunications",
  "Transportation & Warehousing",
  "Travel Agencies & Tour Operations",
  "Veterinary Services & Animal Care",
  "Waste Management & Recycling",
  "Wholesale Trade",
] as const;

export type Industry = (typeof INDUSTRIES)[number];
